apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: InfluxDB-JMeter
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: jmeter
    user: jmeter
    password: jmeter123
    editable: true
    jsonData:
      httpMode: GET
      version: InfluxQL